# Generated by Django 5.0.4 on 2024-05-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_alter_column_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
