# Generated by Django 5.0.4 on 2024-05-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
