# Generated by Django 5.0.4 on 2024-05-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0004_alter_column_options_alter_task_options_column_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinvitation',
            name='project',
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_api.team'),
            preserve_default=False,
        ),
    ]
