# Generated by Django 5.0.4 on 2024-05-31 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_customreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomReport',
        ),
    ]
